const USER_TYPE = Object.freeze({
   ATTENDEE: "ATTENDEE",
   ORGANIZER: "ORGANIZER",
});

const USER_FIELD = Object.freeze({
   ID: "ID",
   EMAIL: "email",
   PHONE: "phone",
});

const VERIFIED_STATUS = Object.freeze({
   BOTH_VERIFIED: "BOTH_VERIFIED",
   EMAIL_VERIFIED: "EMAIL_VERIFIED",
   PHONE_VERIFIED: "PHONE_VERIFIED",
   UNVERIFIED: "UNVERIFIED",
});

const REGISTRATION_STATUS = Object.freeze({
   REGISTERED: "REGISTERED",
   UNREGISTERED: "UNREGISTERED",
   WAITLISTED: "WAITLISTED",
});

const PAYMENT_STATUS = Object.freeze({
   PENDING: "PENDING",
   SUCCESS: "SUCCESS",
   FAILED: "FAILED",
});

module.exports = {
   USER_TYPE,
   USER_FIELD,
   VERIFIED_STATUS,
   REGISTRATION_STATUS,
   PAYMENT_STATUS,
};
